// Fixture builder : produit complet verifie, construit uniquement pour les tests.
export function verifiedProduct(overrides = {}) {
  return {
    product_id: 'test-prod-001',
    product_name: 'Test Walking Pad 2026',
    brand: 'TestBrand',
    category: 'fitness',
    subcategory: 'tapis-de-marche',
    asin: 'B0TEST0001',
    amazon_url: 'https://www.amazon.ca/dp/B0TEST0001',
    affiliate_url: 'https://www.amazon.ca/dp/B0TEST0001?tag=testtag-20',
    price_cad: 499.99,
    currency: 'CAD',
    rating: 4.4,
    review_count: 212,
    product_type: 'tapis de marche pliable',
    key_features: 'Moteur silencieux | Vitesse 10 km/h | Pliage compact',
    specifications: 'Vitesse maximale: 10 km/h | Poids maximal utilisateur: 120 kg',
    pros: 'Encombrement réduit | Silence',
    cons: 'Inclinaison non réglable',
    ideal_for: 'Bureaux | Petits espaces',
    use_cases: 'Marche sous bureau',
    positioning: 'Un choix solide pour la marche au bureau.',
    keyword_cluster: 'tapis-de-marche',
    search_intent: 'commercial',
    content_angles: 'walking pad bureau',
    faq_topics: 'Quelle est sa vitesse maximale ? | Est-il bruyant ?',
    source: 'fiche vérifiée (test)',
    data_status: 'VALIDATED',
    verification_status: 'VERIFIED',
    last_checked: new Date().toISOString().slice(0, 10),
    date_added: new Date().toISOString().slice(0, 10),
    article_status: 'NOT_STARTED',
    article_url: '',
    schema_type: 'Product',
    primary_keyword: 'walking pad bureau',
    secondary_keywords: 'tapis de marche pliable',
    ...overrides
  };
}

export function asSheetRaw(product) {
  return {
    product_id: product.product_id,
    product_name: product.product_name,
    brand: product.brand,
    category: product.category,
    subcategory: product.subcategory,
    ASIN: product.asin,
    Amazon_URL: product.amazon_url,
    affiliate_URL: product.affiliate_url,
    price_CAD: product.price_cad,
    currency: product.currency,
    rating: product.rating,
    review_count: product.review_count,
    product_type: product.product_type,
    key_features: product.key_features,
    specifications: product.specifications,
    pros: product.pros,
    cons: product.cons,
    ideal_for: product.ideal_for,
    use_cases: product.use_cases,
    positioning: product.positioning,
    keyword_cluster: product.keyword_cluster,
    search_intent: product.search_intent,
    content_angles: product.content_angles,
    faq_topics: product.faq_topics,
    source: product.source,
    data_status: product.data_status,
    verification_status: product.verification_status,
    last_checked: product.last_checked,
    date_added: product.date_added,
    article_status: product.article_status,
    schema_type: product.schema_type
  };
}